name: Check Pod Status and Notify Slack

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes, adjust as needed
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-pods:
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubeconfig for multiple clusters
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_K3S }}" > ~/.kube/config-k3s
          echo "${{ secrets.KUBECONFIG_K8S }}" > ~/.kube/config-k8s
          export KUBECONFIG=~/.kube/config-k3s:~/.kube/config-k8s
          # Verify the configuration by listing all contexts
          kubectl config get-contexts

      - name: Get status of all pods
        id: pod_status
        run: |
          export KUBECONFIG=~/.kube/config-k3s:~/.kube/config-k8s
          # Check pod statuses
          FAILED_PODS=$(kubectl get pods -A --field-selector=status.phase!=Running,status.phase!=Succeeded -o json | jq -r '.items[] | "\(.metadata.namespace)/\(.metadata.name) - \(.status.phase) - \(.status.containerStatuses[0].state.waiting.reason)"')
          
          # Export the failed pods list as a GitHub Actions environment variable
          echo "FAILED_PODS<<EOF" >> $GITHUB_ENV
          echo "$FAILED_PODS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check for failed or crashed pods
        if: env.FAILED_PODS != ""
        run: |
          echo "There are failed or crashed pods. Preparing Slack notification."

      - name: Send Slack Notification
        if: env.FAILED_PODS != ""
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "channel": "#your-slack-channel",  # Replace with your channel name
              "username": "K8s Pod Monitor",
              "text": "*Attention:* The following pods are not in Running state:\n```${{ env.FAILED_PODS }}```",
              "icon_emoji": ":warning:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
